version: '3'

services:
  db:
    image: postgres
    container_name: postgres-rpg-test
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "rpg-db-test"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
